#HTTP


#GET
    #SOLICITA PARA UM END POINT
    #UTILIZADO PARA RETORNAR DADOS
#POST
    #ADICIONA UM VALOR E INSERIR INFORMACOES
    #
#PUT
    #SERVE PARA FAZER ATUALIZACOES DE INFORMACOES
    
#DELETE
    #REMOVE AS INFORMACOES
    
#PATCH

    #ATUALIZA INFORMACOES PARCIAIS, NAO TODAS AS INFOS
    
    
    
#CODIGOS DE RESPONSE:

#100 - 199 - INFORMACOES
#200 - 299 - SUCESSO
#300 - 399 - REDIRECIONA
#400 - 499 - ERROS DO CLIENTE
#500 - 599 - ERRO DO SERVER    
    
    
    
    
#DOCUMENTACAO DA API
#MOSTRA COMO A API VAI FUNCIONAR    